# Generated by Django 5.0.4 on 2024-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('target_type', models.CharField(max_length=10)),
                ('target', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_created', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinName', models.CharField(max_length=10)),
                ('coinSymbol', models.CharField(max_length=5)),
            ],
        ),
    ]
