# Generated by Django 5.0.4 on 2024-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinName',
            field=models.CharField(max_length=100),
        ),
    ]
