# Generated by Django 5.0.4 on 2024-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0002_alter_coin_coinname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinSymbol',
            field=models.CharField(max_length=20),
        ),
    ]
