# Generated by Django 5.0.4 on 2024-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0003_alter_coin_coinsymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='validuntil',
            field=models.DateTimeField(default='2024-05-03 10:05'),
        ),
    ]
