# Generated by Django 5.0.4 on 2024-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0005_alert_status_alter_alert_validuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='validuntil',
            field=models.DateTimeField(default='2024-05-03 10:57'),
        ),
    ]
