# Generated by Django 5.0.4 on 2024-05-03 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0006_alter_alert_validuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='validuntil',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
