# Generated by Django 5.0.4 on 2024-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0007_alter_alert_status_alter_alert_validuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('fulfilled', 'Fullfilled')], default='active', max_length=10),
        ),
    ]
