# Generated by Django 5.0.4 on 2024-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0008_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='recipient',
            field=models.CharField(default='+2348133560042', max_length=15),
        ),
    ]
