# Generated by Django 5.0.4 on 2024-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_data', '0009_alert_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='target_directtion',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
