# Generated by Django 5.0.4 on 2024-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('target_type', models.CharField(max_length=10)),
                ('target', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_created', models.CharField(max_length=20)),
            ],
        ),
    ]
