# Generated by Django 5.0.4 on 2024-04-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinName', models.CharField(max_length=10, unique=True)),
                ('coinSymbol', models.CharField(max_length=5)),
            ],
        ),
    ]
