# Generated by Django 5.0.4 on 2024-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='CoinName',
            field=models.CharField(max_length=10),
        ),
    ]
