# Generated by Django 5.0.4 on 2024-04-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_coin_coinname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='CoinName',
            new_name='coinName',
        ),
    ]
